Twilight-Studioo/production

src/Assets/Resource/VFX.meta
src/Assets/Resource/VFX/swap_effect.meta
src/Assets/Resource/VFX/swap_effect/Swap_effect.vfx
src/Assets/Resource/VFX/swap_effect/Swap_effect.vfx.meta
src/Packages/manifest.json
src/Packages/packages-lock.json
src/ProjectSettings/VFXManager.asset

- visual effect graph のパッケージを追加
- swap effect の追加

add visual effect & swap effect

---

src/Assets/Contents/Player.meta
src/Assets/Contents/Player/Animation.meta
src/Assets/Contents/Player/Animation/Player_standby.controller
src/Assets/Contents/Player/Animation/Player_standby.controller.meta
src/Assets/Contents/Player/Animation/Player_standby.fbx
src/Assets/Contents/Player/Animation/Player_standby.fbx.meta
src/Assets/Scenes/Tests/Player_animation.unity
src/Assets/Scenes/Tests/Player_animation.unity.meta

主人公の待機モーション

---

src/Assets/Contents/VFX/orb.meta
src/Assets/Contents/VFX/orb/orb.vfx
src/Assets/Contents/VFX/orb/orb.vfx.meta
src/Assets/Prefabs/selectingEffect.prefab
src/Assets/Prefabs/selectingEffect.prefab.meta

Contents/VFX/orb を追加
Prefabs/selectingEffect を追加

add selecting effect

---

src/Assets/Contents/VFX/swap_effect/Swap_effect.vfx

spawn を single burnst に変更
変数に Lifetime を追加
それらに合わせて調整

fix swap effect

---

src/Assets/Contents/Shader/slashShaderNormal.shadergraph
src/Assets/Contents/Shader/slashShaderNormal.shadergraph.meta
src/Assets/Contents/VFX/slash_effect/slashEffectNormal.vfx
src/Assets/Contents/VFX/slash_effect/slashEffectNormal.vfx.meta
src/Assets/Prefabs/NormalSlash.prefab
src/Assets/Prefabs/NormalSlash.prefab.meta

add normal slash effect

---

src/Assets/Prefabs/SwapItem.prefab
src/Assets/Scenes/Template/Stage.unity
src/Assets/Scenes/Template/StageTemplate.scenetemplate
src/Assets/Settings/Renderer/SampleSceneProfile.asset
src/Assets/lilToon/Editor/CurrentRP.txt

テンプレートステージの環境の変更

---

src/Assets/Editor/Tests/Common.meta
src/Assets/Editor/Tests/Common/Editor.Tests.Common.asmdef
src/Assets/Editor/Tests/Common/Editor.Tests.Common.asmdef.meta
src/Assets/Editor/Tests/Common/EditorTestEx.cs
src/Assets/Editor/Tests/Common/EditorTestEx.cs.meta
src/Assets/Editor/Tests/Common/SingleInjectionClassTest.cs
src/Assets/Editor/Tests/Common/SingleInjectionClassTest.cs.meta
src/Assets/Editor/Tests/Model.meta
src/Assets/Editor/Tests/Model/Editor.Tests.Model.asmdef
src/Assets/Editor/Tests/Model/Editor.Tests.Model.asmdef.meta
src/Assets/Editor/Tests/Model/PlayerModelTest.cs
src/Assets/Editor/Tests/Model/PlayerModelTest.cs.meta
src/Assets/Scripts/Feature/Model/PlayerModel.cs
src/Assets/Scripts/Tests/Model.meta
src/Assets/Scripts/Tests/Model/PlayerModelPlayModeTest.cs
src/Assets/Scripts/Tests/Model/PlayerModelPlayModeTest.cs.meta

:green_heart: test: PlayerModelテスト追加

---

src/Assets/Editor/Tests/View/PlayerAnimationExtensionTest.cs
src/Assets/Scripts/Core/Utilities/MonoBehaviourExtension.cs
src/Assets/Scripts/Core/Utilities/MonoBehaviourExtension.cs.meta
src/Assets/Scripts/Feature/Interface/IPlayerAnimator.cs
src/Assets/Scripts/Feature/View/AnimationWrapper.cs
src/Assets/Scripts/Feature/View/PlayerAnimationExtension.cs
src/Assets/Scripts/Feature/View/PlayerView.cs
src/Assets/Scripts/Tests/Core.meta
src/Assets/Scripts/Tests/Core/Utilities.meta
src/Assets/Scripts/Tests/Core/Utilities/MonoBehaviourExtensionTest.cs
src/Assets/Scripts/Tests/Core/Utilities/MonoBehaviourExtensionTest.cs.meta
src/Assets/Scripts/Tests/Tests.asmdef

- "IsAttacking"の追加
- "IsFalling":Trueが呼ばれない不具合修正

add isAttacking & fixed IsFalling

---

.github/workflows/code-check-build.yml
.github/workflows/non-check-ci.yml
.gitignore
scripts/test_result_convert_md.rb

- test終了時のコメントの見た目修正
- *.csやScripts以下に変更がないときもcommentを出し、styleも統一

:bento: chore: CIワークフローとテストレポート更新

---

.github/workflows/code-check-build.yml
.github/workflows/non-check-ci.yml
src/Assets/Prefabs/Effect/Swap Effect.prefab
src/Assets/Prefabs/Player.prefab
src/Assets/Prefabs/SwapItem.prefab
src/Assets/Prefabs/System/Statics.prefab
src/Assets/Scripts/Core/Utilities/Effect.meta
src/Assets/Scripts/Core/Utilities/Effect/EffectInstance.cs
src/Assets/Scripts/Core/Utilities/Effect/EffectInstance.cs.meta
src/Assets/Scripts/Core/Utilities/Effect/EffectManager.cs
src/Assets/Scripts/Core/Utilities/Effect/EffectManager.cs.meta
src/Assets/Scripts/Feature/Component/Environment/SwapEffectFactory.cs
src/Assets/Scripts/Feature/Component/Environment/SwapEffectFactory.cs.meta
src/Assets/Scripts/Feature/Component/VFXView.cs
src/Assets/Scripts/Feature/Interface/IPlayerView.cs
src/Assets/Scripts/Feature/Presenter/PlayerPresenter.cs
src/Assets/Scripts/Feature/Presenter/SwapPresenter.cs
src/Assets/Scripts/Feature/View/PlayerView.cs
src/Assets/Scripts/Feature/View/SwapView.cs
src/Assets/Scripts/Main/Controller/MainController.cs
src/Assets/Scripts/Main/Installer/MainInstaller.cs

- EffectManagerクラスの実装
- エフェクトのインスタンスを管理するための汎用的な EffectManager クラスを作成。
- エフェクトオブジェクトとその使用回数、最終使用時刻を保持する EffectInstance クラスを導入。
- 使用頻度に応じたプールの動的な拡張・縮小をサポート。
- 一定時間使用されなかったエフェクトを自動的に破棄する機能を追加。
- SwapEffectFactoryの実装
- effectPrefab、effectLifetime などの設定を このクラスを経由して動的に管理
- 
- リソース管理とパフォーマンスの最適化
- EffectInstance クラスを使用して、各エフェクトの使用回数と最終使用時刻を追跡。
- 一定の条件（例: 最後の使用からの経過時間や使用回数）に基づいてプールを自動調整。
---
- testクラスの実装
- 必要に応じて、異なる種類のエフェクトに対するプールのサイズや管理方法をカスタマイズ可能にするさらなる改善
resolved #68

:sparkles: feat: エフェクト管理機能追加

---

src/Assets/Editor/Tests/Main/Editor.Tests.Main.asmdef
src/Assets/Editor/Tests/Main/EnemyFactoryTest.cs
src/Assets/Editor/Tests/Main/EnemyFactoryTest.cs.meta
src/Assets/Scripts/Feature/Common/Constants/EnemyType.cs
src/Assets/Scripts/Feature/Interface/IObjectUtil.cs
src/Assets/Scripts/Feature/Interface/IObjectUtil.cs.meta
src/Assets/Scripts/Main/Factory/EnemyFactory.cs
src/ProjectSettings/BurstAotSettings_Android.json
src/ProjectSettings/BurstAotSettings_StandaloneOSX.json
src/ProjectSettings/CommonBurstAotSettings.json
src/ProjectSettings/Packages/com.unity.testtools.codecoverage/Settings.json

Burst AOT設定を追加し、EnemyFactoryのテストとIObjectUtilインターフェースを追加しました。敵タイプにNoneを追加し、カバレッジ設定を更新しました。

:bento: chore: Burst AOT設定を追加し、テストを拡張

---

.github/workflows/assign-author.yml

:green_heart: feat: auto assignのaction追加

---

.github/CODEOWNERS

リポジトリのディレクトリごとのコード所有者を設定。これによりコードレビューが効率的に行えるようになります。
`.github/CODEOWNERS`ファイルの追加
N/A
N/A
N/A
N/A

:bento: chore: CODEOWNERSファイル追加

---

src/Assets/Scripts/Feature/View/PlayerView.cs

:recycle: refactor: Coroutine呼び出しをUniqueStartCoroutineに変更

---

src/Assets/Prefabs/System/Statics.prefab
src/Assets/Scenes/Template/StageTemplate.scenetemplate

selecterEffectのtemplate反映
N/A
N/A
N/A
N/A

template stageの更新忘れ

---

src/Assets/Scripts/Feature/Presenter/PlayerPresenter.cs
src/Assets/Scripts/Main/Controller/MainController.cs

コメントアウトされたVoltageValue追加の処理とそれをUIに反映する処理の呼び出しを追加
- close #~~
N/A
- 適切かチェックお願いします
- N/A

AddVoltageSwapの呼び出しを追加

---

src/Assets/Scenes/TestStage/StageTemplate.scenetemplate

dependenciesの不要なクローンを削除
N/A
N/A
N/A
N/A

:bug: fix: 依存関係の整合性を修正

---

src/Assets/Contents/Player/Model/Materials/lil_body.mat
src/Assets/Contents/Player/Model/Materials/lil_face.mat
src/Assets/Contents/Player/Model/Materials/lil_limbs.mat

fix player texture

---

src/Assets/Prefabs/Field/DamageArea.prefab
src/Assets/Prefabs/Field/DamageArea.prefab.meta
src/Assets/Prefabs/SwapItem.prefab
src/Assets/Scripts/Core/Utilities/Rays.cs
src/Assets/Scripts/Feature/Component/DamagedTrigger.cs
src/Assets/Scripts/Feature/Component/Enemy/SimpleEnemy1Agent.cs
src/Assets/Scripts/Feature/Component/Enemy/SimpleEnemy2Agent.cs
src/Assets/Scripts/Feature/Component/Environment/DamageArea.cs
src/Assets/Scripts/Feature/Component/Environment/DamageArea.cs.meta
src/Assets/Scripts/Feature/Interface/ISwappable.cs
src/Assets/Scripts/Feature/View/SwapView.cs
src/ProjectSettings/TagManager.asset

あたったらダメージを与えるようにした
- #190 
プレイヤーにダメージを与えることは確認
スワップアイテムと触れると消すようにしたかったができなかった

add damage area

---

src/Assets/Contents/VFX/Beam/Beam_effect.vfx
src/Assets/Contents/VFX/orb/orb.vfx
src/Assets/Contents/VFX/slash_effect/slashEffectNormal.vfx
src/Assets/Contents/VFX/slash_effect/slash_effect.vfx
src/Assets/Contents/VFX/swap_effect/Swap_effect.vfx
src/Assets/Contents/VFX/swap_effect/swap_UVs.vfx

#193 ここのPRの何かの影響でエフェクトが消えていたバグの修正
effectファイルがマージのタイミングで破損していたようなので(vfxのeditor?でも表示されていなかった)ファイルのformatに合わない部分を手動で編集し直した
N/A
-

swapEffectが表示されない不具合修正

---

src/Assets/Scenes/Tests/DroneTest.unity
src/Assets/Scripts/Core/Utilities/GizmoManager.cs
src/Assets/Scripts/Core/Utilities/Health/HealthBarManager.cs
src/Assets/Scripts/Core/Utilities/ObjectFactory.cs
src/Assets/Scripts/Feature/Component/Enemy/DroneAgent.cs
src/Assets/Scripts/Feature/Component/Enemy/SimpleEnemy1Agent.cs
src/Assets/Scripts/Feature/Component/Enemy/SimpleEnemy2Agent.cs
src/Assets/Scripts/Feature/Component/Environment/ItemSpawner.cs
src/Assets/Scripts/Feature/Component/Environment/PlayerStart.cs
src/Assets/Scripts/Feature/Interface/IEnemyAgent.cs
src/Assets/Scripts/Feature/Presenter/EnemyPresenter.cs
src/Assets/Scripts/Feature/View/PlayerView.cs
src/Assets/Scripts/Main/Controller/MainController.cs
src/Assets/Scripts/Main/Factory/EnemyFactory.cs

`ObjectFactory` をシングルトンクラスに変更し、主要メソッドをインスタンスメソッドにしました。 
`SetPlayerTransform` メソッドが消えた！
- close #~~
-

:recycle: refactor: `ObjectFactory` をシングルトンクラスに変更

---

src/Assets/Prefabs/CircularSaw.prefab
src/Assets/Scenes/Tests/SelectEffectTest.unity
src/Assets/Scripts/Feature/Component/CircularSaw.cs
src/Assets/Scripts/Feature/Component/DamagedTrigger.cs
src/Assets/Scripts/Feature/View/SwapView.cs

回転方向を選択できる機能の追加
丸鋸がスワップ後に回転方向に飛んでいく要素を追加
敵に当たった時にダメージを与えられる機能を追加
DamagedTrigger.csにスワップしたかの関数を追加
- close #~~
-

runaway circularsaw

---

src/Assets/Scripts/Core/Utilities/Effect/EffectManager.cs

:bug: fix: エフェクト生成のnullチェック追加

---

src/Assets/Scripts/Feature/View/PlayerView.cs

- close #~~
- [全方向でエフェクトが正しく生成されているか ]
-

斬撃が変な方向に出ていたのを修正

---

src/Assets/Contents/Gimmicks.meta
src/Assets/Contents/Gimmicks/Circlesaw.meta
src/Assets/Contents/Gimmicks/Circlesaw/Models.meta
src/Assets/Contents/Gimmicks/Circlesaw/Models/Blades_only.fbx
src/Assets/Contents/Gimmicks/Circlesaw/Models/Blades_only.fbx.meta
src/Assets/Prefabs/CircularSaw.prefab
src/Assets/Scenes/Tests/SelecterTest.unity
src/Assets/Scripts/Feature/Component/CircularSaw.cs

リポップするように実装
丸のこのモデルを追加
- close #~~
-

リポップするように実装

---

src/Assets/Scripts/Feature/Component/Environment/ItemSpawner.cs

spawnerの修正
- stage-ichiでdistanceが3になっているので要修正

:bug: fix: Item spawning distanceチェックの修正

---

.github/workflows/unified-check-ci.yml
scripts/test_result_convert_md.rb

PR詳細の出力をCI設定とスクリプトから削除しました。これにより、出力が簡潔になります。

:recycle: refactor: PR詳細の出力を削除

---

src/Assets/Scenes/Template/Stage.unity
src/Assets/Scripts/Feature/Component/Enemy/SimpleEnemy2Agent.cs
src/Assets/Scripts/Feature/Component/Environment/EnemyStart.cs
src/Assets/Scripts/Feature/Interface/IEnemyPresenter.cs
src/Assets/Scripts/Feature/Presenter/EnemyPresenter.cs
src/Assets/Scripts/Main/Controller/MainController.cs
src/Assets/Scripts/Main/Factory/EnemyFactory.cs
src/Packages/packages-lock.json

:recycle: refactor: プレイヤー参照の取得方法を統一 agentの動作開始logicの修正

---

src/Assets/Scenes/TestStage/Stage.unity

fix stage conflict

---

src/Assets/Scripts/Feature/Component/DamagedTrigger.cs
src/Assets/Scripts/Feature/Component/Environment/EnemyStart.cs
src/Assets/Scripts/Feature/Component/VolumeController.cs
src/Assets/Scripts/Feature/Interface/IGameController.cs
src/Assets/Scripts/Feature/Interface/IPlayerStateDispatcher.cs
src/Assets/Scripts/Feature/Interface/IPlayerStateDispatcher.cs.meta
src/Assets/Scripts/Feature/Model/Feature.Model.asmdef
src/Assets/Scripts/Feature/Model/PlayerModel.cs
src/Assets/Scripts/Feature/Model/SwapModel.cs
src/Assets/Scripts/Feature/Presenter/PlayerPresenter.cs
src/Assets/Scripts/Feature/Presenter/SwapPresenter.cs
src/Assets/Scripts/Main/Controller/MainController.cs
src/Assets/Scripts/Tests/Model/PlayerModelPlayModeTest.cs

- close #202 
- close #188 
- close #186 
-

swap系の処理をイベント駆動に修正

---

src/Assets/Prefabs/Enemy/Drone.prefab

ドローンの向きの調整

---

src/Assets/Prefabs/Camera.prefab
src/Assets/Settings/Main Camera Blends.asset
src/Assets/Settings/Main Camera Blends.asset.meta

add camera blends setting

---

src/Assets/Prefabs/CircularSaw.prefab

CircularSaw Prefabのz position x,y rotationをfreeze
- close #~~
-スクリプトいじってないです

CircularSawのPrefabを修正

---

src/Assets/Scenes/Tests/SelectEffectTest.unity
src/Assets/Scripts/Feature/Component/AccelerationPlate.cs

左右方向の加速をboolで選択可能にした
- close #~~
-

加速方向を選択を追加

---

src/Assets/Scenes/Tests/SelectEffectTest.unity
src/Assets/Scripts/Feature/Component/AccelerationPlate.cs
src/Assets/Scripts/Feature/Component/CircularSaw.cs

CreateGameObjectの複製するオブジェクトをCicularsawのPrefabから丸鋸の刃のみに変更
- close #~~
-

スワップできないバグを修正

---

src/Assets/Contents/VFX/Voltage_effect.meta
src/Assets/Contents/VFX/Voltage_effect/Model.meta
src/Assets/Contents/VFX/Voltage_effect/Model/gem1.fbx
src/Assets/Contents/VFX/Voltage_effect/Model/gem1.fbx.meta
src/Assets/Contents/VFX/Voltage_effect/Voltage_effect.vfx
src/Assets/Contents/VFX/Voltage_effect/Voltage_effect.vfx.meta
src/Assets/Contents/VFX/Voltage_effect/Voltage_shader.shadergraph
src/Assets/Contents/VFX/Voltage_effect/Voltage_shader.shadergraph.meta
src/Assets/Prefabs/Effect/Voltage_effect.prefab
src/Assets/Prefabs/Effect/Voltage_effect.prefab.meta
src/Assets/Prefabs/Player.prefab

ボルテージがたまったときのエフェクトを実装
プレイヤーのprefabに追加
- close #~~
エフェクトの Voltage を変えることで見た目が変わる

add voltage effect and modify player prefab

---

src/Assets/Scripts/Feature/Component/Enemy/SimpleEnemy1Agent.cs
src/Assets/Scripts/Feature/Component/Enemy/SimpleEnemy2Agent.cs

:bug: fix: OnSwapでの位置更新修正

---

src/Assets/Scripts/Core/Utilities/CloudService.cs
src/Assets/Scripts/Core/Utilities/CloudService.cs.meta
src/Assets/Scripts/Core/Utilities/Core.Utilities.asmdef
src/Assets/Scripts/Feature/Component/Enemy/DroneAgent.cs
src/Assets/Scripts/Feature/Interface/IEnemyAgent.cs
src/Assets/Scripts/Feature/View/EnemyView.cs
src/Assets/Scripts/Main/Controller/RootManager.cs
src/Assets/Scripts/Main/Controller/RootManager.cs.meta
src/Assets/Scripts/Main/Installer/RootInstaller.cs
src/Packages/manifest.json
src/Packages/packages-lock.json

UnityServicesのCloudSave, LeaderBoards, Authenticationのimportと初期化
- close #~~
-

cloud セーブとリーダボード基盤を整えた

---

src/ProjectSettings/ProjectSettings.asset

:bento: chore: バージョンを0.2.0に更新

---

src/Assets/Scripts/Main/Controller/GameController.cs

スワップ後にvoltageが追加されるようになっていたが、終了時の分岐がおかしかった
- close #292 
-

スワップ後処理にnullチェックを追加し、スワップキャンセルを改善

---

src/Assets/Scripts/Feature/Component/Enemy/SimpleEnemy1Agent.cs
src/Assets/Scripts/Feature/Component/Enemy/SimpleEnemy2Agent.cs
src/Assets/Scripts/Feature/View/EnemyView.cs

:bug: fix: エージェントのヒット処理を修正

---

src/Assets/Contents/Smasher.meta
src/Assets/Contents/Smasher/smasyaKARIfix.fbx
src/Assets/Contents/Smasher/smasyaKARIfix.fbx.meta

smasher kari model ADD

---

src/Assets/Scripts/Feature/Common/Parameter/CharacterParams.cs
src/Assets/Scripts/Feature/Model/PlayerModel.cs
src/Assets/Scripts/Feature/Presenter/PlayerPresenter.cs

:bento: chore: パラメータとボルテージ回復処理を更新

---

src/Assets/Scripts/Feature/Model/PlayerModel.cs

:sparkle: feat: ダメージを与えた後にvoltageを回復させる

---

src/Assets/Scripts/Feature/Common/Parameter/CharacterParams.cs
src/Assets/Scripts/Feature/Model/PlayerModel.cs

#321 の追加実装(忘れてた)
- close #~~
-

feat: ダメージ後のvoltage回復を追加

---

src/Assets/Prefabs/Enemy/ZakoBullet.prefab
src/Assets/Scripts/Feature/Component/DamagedTrigger.cs
src/Assets/Scripts/Feature/Component/Enemy/SimpleEnemy2Agent.cs

敵が発射する弾がプレイヤーを向くように修正しました。この変更により的確にプレイヤーを狙う挙動が再現されます。その他、使用していない変数とコンポーネントを削除しました。
- close #324 
- いつからか分からないが、meshを置き換えたことでswapモード中のhighlightは効いていない

:bug: fix: 敵の発射物の向き修正

---

src/Assets/Contents/UI/Voltage.meta
src/Assets/Contents/UI/Voltage/voltage_1.PNG.meta
src/Assets/Contents/UI/Voltage/voltage_2.PNG.meta
src/Assets/Contents/UI/Voltage/voltage_3.PNG.meta
src/Assets/Contents/UI/Voltage/voltage_4.PNG.meta

fix meta file

---

src/Assets/Prefabs/Field/FixedLoadSceneArea.prefab
src/Assets/Prefabs/Field/FixedLoadSceneArea.prefab.meta
src/Assets/Scenes/Template/Stage.scenetemplate
src/Assets/Scenes/Template/Stage.unity
src/Assets/Scripts/Feature/Component/FixedLoadSceneArea.cs
src/Assets/Scripts/Feature/Component/FixedLoadSceneArea.cs.meta

プレイヤーがトリガーに入った際に指定シーンをロードする新コンポーネントを追加しました。SceneNameが空の場合に警告を表示します。プレハブと関連シーンテンプレートも更新されています。
- close #~~
-

:sparkles: feat: 指定シーンに遷移するエリアを追加

---

src/Assets/Scripts/Core/Utilities/Parameter/VectorToggleDrawer.cs
src/Assets/Scripts/Feature/Common/Parameter/SmasherPramsEditor.cs

エディター専用コードをプリプロセッサディレクティブで囲みました。これにより、ビルド時の不要なエラーを防ぎます。
- close #~~
-

:bug: fix: ビルド時のエラー修正

---

src/Assets/Prefabs/System/Canvas.prefab
src/Assets/Prefabs/UI/HPBar.prefab
src/Assets/Prefabs/UI/VoltageBar.prefab

fix ui aspect and color

---

src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_Jirai.fbx
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_Jirai.fbx.meta
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_Landing.fbx
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_Landing.fbx.meta
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_damage.fbx
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_damage.fbx.meta
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_forwardattackL.fbx
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_forwardattackL.fbx.meta
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_hirate.fbx
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_hirate.fbx.meta
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_jump.fbx
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_jump.fbx.meta
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_kick.fbx
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_kick.fbx.meta
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_rakka.fbx
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_rakka.fbx.meta
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_standby.fbx
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_standby.fbx.meta
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_upper.fbx
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_upper.fbx.meta
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/kuutyu.fbx
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/kuutyu.fbx.meta

スマッシャーのモーションの修正データを入れました。smasherKARI_1208のフォルダを使ってください

---

src/Assets/Contents/Smasher/Animation/smasherKARI_1208.meta
src/Assets/Editor/Tests/Main/EnemyFactoryTest.cs
src/Assets/Prefabs/Effect/Enemy_damage_effect.prefab
src/Assets/Prefabs/Effect/Player_damage_effect.prefab
src/Assets/Prefabs/System/Statics.prefab
src/Assets/Scenes/Template/Stage.unity
src/Assets/Scripts/Core/Utilities/Effect/EffectManager.cs
src/Assets/Scripts/Feature/Component/Environment/DamageEffectFactory.cs
src/Assets/Scripts/Feature/Component/Environment/DamageEffectFactory.cs.meta
src/Assets/Scripts/Feature/Interface/IEnemy.cs
src/Assets/Scripts/Feature/Interface/IPlayerView.cs
src/Assets/Scripts/Feature/Presenter/PlayerPresenter.cs
src/Assets/Scripts/Feature/View/EnemyView.cs
src/Assets/Scripts/Feature/View/PlayerView.cs
src/Assets/Scripts/Main/Factory/EnemyFactory.cs
src/Assets/Scripts/Main/Installer/GameInstaller.cs

DamageEffectFactoryを導入し、プレイヤーや敵がダメージを受けた際にエフェクトを表示する処理を実装。エフェクトの再生には位置や回転情報を考慮。
- close #351 
- close #352 
-

:sparkles: feat: ダメージエフェクト機能を追加

---

src/Assets/Prefabs/SwapItem/SwapItem.prefab
src/Assets/Prefabs/SwapItem/SwapItem_Gravity.prefab
src/Assets/Prefabs/SwapItem/swapitem_greendrum.prefab
src/Assets/Prefabs/SwapItem/swapitem_stealbox.prefab
src/Assets/Prefabs/SwapItem/swapitem_woodbox.prefab
src/Assets/Prefabs/SwapItem/zakoPartArmR.prefab
src/Assets/Prefabs/SwapItem/zakoPartArmWeld 1.prefab
src/Assets/Prefabs/SwapItem/zakoPartLeg.prefab
src/Assets/Scenes/Template/Stage.scenetemplate
src/Assets/Scenes/Template/Stage.unity
src/Assets/Scripts/Core/Utilities/Tag.meta
src/Assets/Scripts/Core/Utilities/Tag/ITag.cs
src/Assets/Scripts/Core/Utilities/Tag/ITag.cs.meta
src/Assets/Scripts/Core/Utilities/Tag/Tags.cs
src/Assets/Scripts/Core/Utilities/Tag/Tags.cs.meta
src/Assets/Scripts/Feature/Common/Constants/Tag.meta
src/Assets/Scripts/Feature/Common/Constants/Tag/SwapItemTag.cs
src/Assets/Scripts/Feature/Common/Constants/Tag/SwapItemTag.cs.meta
src/Assets/Scripts/Feature/Component/DeleteSpawnItemArea.cs
src/Assets/Scripts/Feature/Component/Environment/DamageArea.cs
src/ProjectSettings/TagManager.asset

ITagインターフェースを導入し、SwapItemタグ判定をリファクタリング。Prefabとスクリプトの整合性を修正。
- close #353
-

:bug: fix: SwapItemタグ関連の仕様変更対応

---

.github/workflows/unified-check-ci.yml
src/.idea/.idea.src/.idea/.gitignore
src/.idea/.idea.src/.idea/indexLayout.xml

PRがマージ済みの場合でも不要なジョブが実行される問題を修正。条件に`github.event.pull_request.merged == false`を追加。
- close #~~
-

:bug: fix: 条件にPR未マージを追加

---

src/Assets/Contents/UI/button.meta
src/Assets/Contents/UI/button/button.PNG
src/Assets/Contents/UI/button/button.PNG.meta

タイキさんのタイトル画面で使用するボタン挿入

---

src/Assets/Contents/Smasher/Animation/BossSmasher (1).controller
src/Assets/Contents/Smasher/Animation/BossSmasher (1).controller.meta
src/Assets/Contents/Smasher/Animation/HandPunch.anim
src/Assets/Contents/Smasher/Animation/HandPunch.anim.meta
src/Assets/Contents/Smasher/Animation/JiraiFix.anim
src/Assets/Contents/Smasher/Animation/JiraiFix.anim.meta
src/Assets/Contents/Smasher/Animation/SmasherHandMask.mask
src/Assets/Contents/Smasher/Animation/SmasherHandMask.mask.meta
src/Assets/Contents/Smasher/Animation/Smasher_Jirai (1).fbx.meta
src/Assets/Contents/Smasher/Animation/Smasher_Landing (1).fbx.meta
src/Assets/Contents/Smasher/Animation/Smasher_damage (1).fbx.meta
src/Assets/Contents/Smasher/Animation/Smasher_forwardattackL (1).fbx.meta
src/Assets/Contents/Smasher/Animation/Smasher_hirate (1).fbx.meta
src/Assets/Contents/Smasher/Animation/Smasher_jump (1).fbx.meta
src/Assets/Contents/Smasher/Animation/Smasher_kick (1).fbx.meta
src/Assets/Contents/Smasher/Animation/Smasher_rakka (1).fbx.meta
src/Assets/Contents/Smasher/Animation/Smasher_standby (1).fbx.meta
src/Assets/Contents/Smasher/Animation/smasherKARI_1208/Smasher_standby.fbx.meta
src/Assets/Contents/Smasher/BossSmasher.fbx
src/Assets/Contents/Smasher/BossSmasher.fbx.meta
src/Assets/Contents/Smasher/BossSmasher.prefab
src/Assets/Contents/Smasher/BossSmasher.prefab.meta

スマッシャーのモデリングを追加した、コンストレイントも動作確認した。BossSmasher.prefab を使ってください。一回アニメーションを確認した、animatorに hand Layer とFix　Layerを仮で追加した。
- close #~~
-

Add smasher model,Add hand animation and JiraiFix animation

---

src/Assets/Scripts/Core/Utilities/ObjectFactory.cs

DDOLの実行をplaymodeに限定

---

src/Assets/Contents/Player/Animation/PlayerAnimatorController.controller
src/Assets/Contents/Player/Animation/player_motion/Player_inJamp.fbx
src/Assets/Contents/Player/Animation/player_motion/Player_inJamp.fbx.meta
src/Assets/Contents/Player/Animation/player_motion/inJamp.anim
src/Assets/Contents/Player/Animation/player_motion/inJamp.anim.meta

主人公の空中モーションの調節を行いました。
モーションはPlayer▶Animation▶player-motion▶Player-inJampというモーションを追加したので、空中モーションとして実装をお願いします。
- close #~~
-

主人公の空中モーション調整

---

src/Assets/Scripts/Feature/Component/Enemy/Smasher.cs

fix health

---

src/Assets/Scenes/Tests/SelectEffectTest.unity
src/Assets/Scripts/Feature/Component/CircularSaw.cs
src/Assets/Scripts/Feature/Component/Enemy/Smasher.cs

丸鋸の修正　瓦礫攻撃のエラーの修正

---

src/Assets/Contents/Build/sutekka.png
src/Assets/Contents/Build/sutekka.png.meta
src/ProjectSettings/ProjectSettings.asset

:sparkles: feat: 新しいアイコン画像を追加

---

src/Assets/Scripts/Feature/Model/SwapModel.cs

swap可能な範囲を入力前方の45度範囲に制限

---

src/Assets/Prefabs/Enemy/Smasher.prefab
src/Assets/Scenes/Tests/SelectEffectTest.unity
src/Assets/Scripts/Feature/Component/Enemy/Smasher.cs
src/Assets/Settings/Enemy/SmasherPrams.asset

地面につかず落下攻撃へのつながりが悪いところがあったため修正
チャージ攻撃中にボスの向きが変わらないように修正
攻撃を受けたときの後ろに飛ばされる動きを修正
- close #~~
-

スマッシャーの動きを修正

---

src/Assets/Scripts/Core/Utilities/ObjectFactory.cs
src/Assets/Scripts/Feature/Component/TitlePlayerAnimation.cs
src/Assets/Scripts/Main/Controller/TitleManager.cs

:sparkles: fix: titleに戻った時の初期化処理を修正
